FROM mcr.microsoft.com/dotnet/sdk:5.0-alpine AS build

ENV PORT 8080
ENV SSH_PORT 2222

WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY appsvcdemobyos/*.csproj ./appsvcdemobyos/
RUN dotnet restore -r linux-musl-x64

# copy everything else and build app
COPY appsvcdemobyos/. ./appsvcdemobyos/
WORKDIR /source/appsvcdemobyos
RUN dotnet publish -c release -o /app -r linux-musl-x64 --self-contained false --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine-amd64
WORKDIR /app
COPY --from=build /app ./

EXPOSE 8080
ENTRYPOINT ["dotnet", "appsvcdemobyos.dll"]

